name: Run CI
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies & build component library
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Build documentation
        run: npm run build:prod
